name: CI
on: push

env:
  REGISTRY_NAME: fintlabsacr
  MODEL_VERSION: 4.0.0
  LIB_VERSION: 4.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Get repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Compute image tag
        run: echo "IMAGE_TAG=${MODEL_VERSION}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_NAME}}.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Building the container
        run: |
          docker build --tag ${{env.REGISTRY_NAME}}.azurecr.io/${{env.REPO_NAME}}:${{env.IMAGE_TAG}} --build-arg VERSION=${{env.LIB_VERSION}} .
